/*************************************
 SLOPE FOR PER TYPE AND GAIN 

**************************************/
#ifndef	SLOPE_h_ 
#define	SLOPE_h_ 

unsigned int Get_K_Slope(unsigned long int kt);
unsigned int Get_J_Slope(unsigned long int jt);
unsigned int Get_T_Slope(unsigned long int ts);
unsigned int Get_E_Slope(unsigned long int et);
unsigned int Get_R_Slope(unsigned long int rt);
unsigned int Get_S_Slope(unsigned long int st);
unsigned int Get_B_Slope(unsigned long int bt);
unsigned int Get_N_Slope(unsigned long int nt); 
unsigned int Get_RTD_Slope(unsigned long int rtd);
unsigned int DO_RTD_TYPE(void);
#endif